"""
Fetch 30 Unsplash photos per city and regenerate destinations-photos.js.
Uses 2 short queries per city for variety (24 total API requests, well under 50/hr limit).
"""
import json
import os
import time
import urllib.request
import urllib.parse

UNSPLASH_KEY = "OKB5oL2NfsMAZkJwHoE41mRfzK0Sk7_6n1OY2RMr2JI"
PER_QUERY = 20  # max per_page we request
OUTPUT = os.path.join(os.path.dirname(__file__), "destinations-photos.js")

# Two short queries per city for variety (~40 candidates, then dedup to top 30)
CITY_QUERIES = {
    "beijing":      ["Beijing China landmark", "Beijing travel"],
    "shanghai":     ["Shanghai China skyline", "Shanghai Bund"],
    "chengdu":      ["Chengdu China street", "Chengdu panda"],
    "lijiang":      ["Lijiang China old town", "Lijiang Yunnan"],
    "sanya":        ["Sanya China beach", "Sanya Hainan"],
    "xian":         ["Xian China ancient", "Xian terracotta"],
    "guilin":       ["Guilin China landscape", "Guilin Li River"],
    "lhasa":        ["Lhasa Tibet Potala", "Lhasa monastery"],
    "zhangjiajie":  ["Zhangjiajie China mountain", "Zhangjiajie pillar"],
    "xiamen":       ["Xiamen China island", "Xiamen Gulangyu"],
    "harbin":       ["Harbin China ice", "Harbin winter"],
    "dunhuang":     ["Dunhuang China desert", "Dunhuang Mogao"],
}


def search_photos(query, per_page=30):
    """Search Unsplash, return list of photo dicts."""
    url = (
        f"https://api.unsplash.com/search/photos"
        f"?query={urllib.parse.quote(query)}"
        f"&orientation=landscape"
        f"&per_page={per_page}"
    )
    req = urllib.request.Request(url, headers={"Authorization": f"Client-ID {UNSPLASH_KEY}"})
    with urllib.request.urlopen(req, timeout=15) as resp:
        data = json.loads(resp.read())
    return data.get("results", [])


def build_photo(p):
    return {
        "id": p["id"],
        "url": p["urls"]["regular"],
        "fullUrl": p["urls"]["full"],
        "thumb": p["urls"]["thumb"],
        "desc": (p.get("description") or p.get("alt_description") or ""),
        "author": p["user"]["name"],
        "authorUrl": p["user"]["links"]["html"] + "?utm_source=nomad&utm_medium=referral",
        "width": p["width"],
        "height": p["height"],
        "blurHash": p.get("blur_hash", ""),
        "likes": p.get("likes", 0),
        "color": p.get("color", ""),
    }


def main():
    output = {}
    total_requests = 0
    target = 30

    for dest_id, queries in CITY_QUERIES.items():
        all_photos = []
        seen = set()

        for qi, query in enumerate(queries):
            print(f"  {dest_id:12s} [{qi+1}/2] \"{query}\" ... ", end="", flush=True)
            try:
                photos = search_photos(query, per_page=PER_QUERY)
                new_count = 0
                for p in photos:
                    if p["id"] not in seen:
                        seen.add(p["id"])
                        all_photos.append(p)
                        new_count += 1
                print(f"{new_count} new ({len(all_photos)} total)")
                total_requests += 1
            except Exception as e:
                print(f"FAILED: {e}")
            time.sleep(1.5)  # be polite to API

        # Sort by likes, take top N
        all_photos.sort(key=lambda p: p.get("likes", 0) or 0, reverse=True)
        output[dest_id] = [build_photo(p) for p in all_photos[:target]]
        print(f"  => {len(output[dest_id])} photos kept (from {len(all_photos)} candidates)")

    # Report
    print(f"\n{'='*55}")
    print(f"Total API requests: {total_requests} / 50 per hour")
    total_photos = 0
    for dest_id in CITY_QUERIES:
        count = len(output.get(dest_id, []))
        total_photos += count
        bar = "#" * count
        print(f"  {dest_id:12s}  {count:2d} photos  {bar}")
    print(f"  {'TOTAL':12s}  {total_photos:2d} photos")
    print(f"{'='*55}")

    # Generate JS
    lines = [
        "// Auto-generated by fetch_city_photos.py",
        "// Unsplash API — curated travel photos for 12 Chinese destinations",
        f"// Generated photos per destination: { {k: len(v) for k, v in output.items()} }",
        "",
        "const destinationPhotos = " + json.dumps(output, ensure_ascii=False, indent=2) + ";",
        "",
    ]
    js_content = "\n".join(lines)
    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write(js_content)

    size_kb = len(js_content.encode("utf-8")) / 1024
    print(f"\nOutput: {OUTPUT} ({size_kb:.0f} KB)")
    print("Done!")


if __name__ == "__main__":
    main()
